name: hw
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.4.0
  flutter_bloc: ^8.0.1
  meta: ^1.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
  